//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_maken
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoneelsLid
    {
        public PersoneelsLid()
        {
            this.Personeelsleden = new HashSet<PersoneelsLid>();
        }
    
        public int PersoneelsNr { get; set; }
        public string Voornaam { get; set; }
        public Nullable<int> ManagerNr { get; set; }
    
        public virtual ICollection<PersoneelsLid> Personeelsleden { get; set; }
        public virtual PersoneelsLid Manager { get; set; }
    }
}
