//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCursus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursisten
    {
        public Cursisten()
        {
            this.Beschermelingen = new HashSet<Cursisten>();
            this.Naam = new Naam();
        }
    
        public int CursistNr { get; set; }
        public Nullable<int> MentorNr { get; set; }
    
        public Naam Naam { get; set; }
    
        public virtual ICollection<Cursisten> Beschermelingen { get; set; }
        public virtual Cursisten Mentor { get; set; }
    }
}
