//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCursus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voorraad
    {
        public int MagazijnNr { get; set; }
        public int ArtikelNr { get; set; }
        public int AantalStuks { get; set; }
        public int RekNr { get; set; }
    }
}
